#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JSONWebService
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="narfdaddy2")]
	public partial class OneBaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertClient(Client instance);
    partial void UpdateClient(Client instance);
    partial void DeleteClient(Client instance);
    #endregion
		
		public OneBaseDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["OneBaseConnectionString2"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public OneBaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OneBaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OneBaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OneBaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Client> Clients
		{
			get
			{
				return this.GetTable<Client>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Clients")]
	public partial class Client : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _numRow;
		
		private System.Nullable<System.DateTime> _datAdded;
		
		private string _vcHow;
		
		private string _vcComment;
		
		private string _vcInsStatus;
		
		private string _vcMcdNo;
		
		private string _vcMltc;
		
		private string _vcName;
		
		private string _vcP;
		
		private string _vcPR;
		
		private string _vcP2;
		
		private string _vcP2R;
		
		private string _vcLang;
		
		private string _vcSSN;
		
		private string _vcSex;
		
		private System.Nullable<System.DateTime> _datDOB;
		
		private string _vcMobil;
		
		private string _vcTransp;
		
		private string _vcAuthNo;
		
		private System.Nullable<System.DateTime> _datAuth;
		
		private System.Nullable<System.DateTime> _datEffectiv;
		
		private string _datExp;
		
		private string _bHHA_Sun;
		
		private string _bHHA_Mon;
		
		private string _bHHA_Tue;
		
		private string _bHHA_Wed;
		
		private string _bHHA_Thu;
		
		private string _bHHA_Fri;
		
		private string _bHHA_Sat;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnumRowChanging(long value);
    partial void OnnumRowChanged();
    partial void OndatAddedChanging(System.Nullable<System.DateTime> value);
    partial void OndatAddedChanged();
    partial void OnvcHowChanging(string value);
    partial void OnvcHowChanged();
    partial void OnvcCommentChanging(string value);
    partial void OnvcCommentChanged();
    partial void OnvcInsStatusChanging(string value);
    partial void OnvcInsStatusChanged();
    partial void OnvcMcdNoChanging(string value);
    partial void OnvcMcdNoChanged();
    partial void OnvcMltcChanging(string value);
    partial void OnvcMltcChanged();
    partial void OnvcNameChanging(string value);
    partial void OnvcNameChanged();
    partial void OnvcPChanging(string value);
    partial void OnvcPChanged();
    partial void OnvcPRChanging(string value);
    partial void OnvcPRChanged();
    partial void OnvcP2Changing(string value);
    partial void OnvcP2Changed();
    partial void OnvcP2RChanging(string value);
    partial void OnvcP2RChanged();
    partial void OnvcLangChanging(string value);
    partial void OnvcLangChanged();
    partial void OnvcSSNChanging(string value);
    partial void OnvcSSNChanged();
    partial void OnvcSexChanging(string value);
    partial void OnvcSexChanged();
    partial void OndatDOBChanging(System.Nullable<System.DateTime> value);
    partial void OndatDOBChanged();
    partial void OnvcMobilChanging(string value);
    partial void OnvcMobilChanged();
    partial void OnvcTranspChanging(string value);
    partial void OnvcTranspChanged();
    partial void OnvcAuthNoChanging(string value);
    partial void OnvcAuthNoChanged();
    partial void OndatAuthChanging(System.Nullable<System.DateTime> value);
    partial void OndatAuthChanged();
    partial void OndatEffectivChanging(System.Nullable<System.DateTime> value);
    partial void OndatEffectivChanged();
    partial void OndatExpChanging(string value);
    partial void OndatExpChanged();
    partial void OnbHHA_SunChanging(string value);
    partial void OnbHHA_SunChanged();
    partial void OnbHHA_MonChanging(string value);
    partial void OnbHHA_MonChanged();
    partial void OnbHHA_TueChanging(string value);
    partial void OnbHHA_TueChanged();
    partial void OnbHHA_WedChanging(string value);
    partial void OnbHHA_WedChanged();
    partial void OnbHHA_ThuChanging(string value);
    partial void OnbHHA_ThuChanged();
    partial void OnbHHA_FriChanging(string value);
    partial void OnbHHA_FriChanged();
    partial void OnbHHA_SatChanging(string value);
    partial void OnbHHA_SatChanged();
    #endregion
		
		public Client()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numRow", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long numRow
		{
			get
			{
				return this._numRow;
			}
			set
			{
				if ((this._numRow != value))
				{
					this.OnnumRowChanging(value);
					this.SendPropertyChanging();
					this._numRow = value;
					this.SendPropertyChanged("numRow");
					this.OnnumRowChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datAdded", DbType="Date")]
		public System.Nullable<System.DateTime> datAdded
		{
			get
			{
				return this._datAdded;
			}
			set
			{
				if ((this._datAdded != value))
				{
					this.OndatAddedChanging(value);
					this.SendPropertyChanging();
					this._datAdded = value;
					this.SendPropertyChanged("datAdded");
					this.OndatAddedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vcHow", DbType="VarChar(50)")]
		public string vcHow
		{
			get
			{
				return this._vcHow;
			}
			set
			{
				if ((this._vcHow != value))
				{
					this.OnvcHowChanging(value);
					this.SendPropertyChanging();
					this._vcHow = value;
					this.SendPropertyChanged("vcHow");
					this.OnvcHowChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vcComment", DbType="VarChar(MAX)")]
		public string vcComment
		{
			get
			{
				return this._vcComment;
			}
			set
			{
				if ((this._vcComment != value))
				{
					this.OnvcCommentChanging(value);
					this.SendPropertyChanging();
					this._vcComment = value;
					this.SendPropertyChanged("vcComment");
					this.OnvcCommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vcInsStatus", DbType="VarChar(100)")]
		public string vcInsStatus
		{
			get
			{
				return this._vcInsStatus;
			}
			set
			{
				if ((this._vcInsStatus != value))
				{
					this.OnvcInsStatusChanging(value);
					this.SendPropertyChanging();
					this._vcInsStatus = value;
					this.SendPropertyChanged("vcInsStatus");
					this.OnvcInsStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vcMcdNo", DbType="VarChar(100)")]
		public string vcMcdNo
		{
			get
			{
				return this._vcMcdNo;
			}
			set
			{
				if ((this._vcMcdNo != value))
				{
					this.OnvcMcdNoChanging(value);
					this.SendPropertyChanging();
					this._vcMcdNo = value;
					this.SendPropertyChanged("vcMcdNo");
					this.OnvcMcdNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vcMltc", DbType="VarChar(50)")]
		public string vcMltc
		{
			get
			{
				return this._vcMltc;
			}
			set
			{
				if ((this._vcMltc != value))
				{
					this.OnvcMltcChanging(value);
					this.SendPropertyChanging();
					this._vcMltc = value;
					this.SendPropertyChanged("vcMltc");
					this.OnvcMltcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vcName", DbType="VarChar(100)")]
		public string vcName
		{
			get
			{
				return this._vcName;
			}
			set
			{
				if ((this._vcName != value))
				{
					this.OnvcNameChanging(value);
					this.SendPropertyChanging();
					this._vcName = value;
					this.SendPropertyChanged("vcName");
					this.OnvcNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vcP", DbType="VarChar(20)")]
		public string vcP
		{
			get
			{
				return this._vcP;
			}
			set
			{
				if ((this._vcP != value))
				{
					this.OnvcPChanging(value);
					this.SendPropertyChanging();
					this._vcP = value;
					this.SendPropertyChanged("vcP");
					this.OnvcPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vcPR", DbType="VarChar(50)")]
		public string vcPR
		{
			get
			{
				return this._vcPR;
			}
			set
			{
				if ((this._vcPR != value))
				{
					this.OnvcPRChanging(value);
					this.SendPropertyChanging();
					this._vcPR = value;
					this.SendPropertyChanged("vcPR");
					this.OnvcPRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vcP2", DbType="VarChar(20)")]
		public string vcP2
		{
			get
			{
				return this._vcP2;
			}
			set
			{
				if ((this._vcP2 != value))
				{
					this.OnvcP2Changing(value);
					this.SendPropertyChanging();
					this._vcP2 = value;
					this.SendPropertyChanged("vcP2");
					this.OnvcP2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vcP2R", DbType="VarChar(50)")]
		public string vcP2R
		{
			get
			{
				return this._vcP2R;
			}
			set
			{
				if ((this._vcP2R != value))
				{
					this.OnvcP2RChanging(value);
					this.SendPropertyChanging();
					this._vcP2R = value;
					this.SendPropertyChanged("vcP2R");
					this.OnvcP2RChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vcLang", DbType="VarChar(100)")]
		public string vcLang
		{
			get
			{
				return this._vcLang;
			}
			set
			{
				if ((this._vcLang != value))
				{
					this.OnvcLangChanging(value);
					this.SendPropertyChanging();
					this._vcLang = value;
					this.SendPropertyChanged("vcLang");
					this.OnvcLangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vcSSN", DbType="Char(9)")]
		public string vcSSN
		{
			get
			{
				return this._vcSSN;
			}
			set
			{
				if ((this._vcSSN != value))
				{
					this.OnvcSSNChanging(value);
					this.SendPropertyChanging();
					this._vcSSN = value;
					this.SendPropertyChanged("vcSSN");
					this.OnvcSSNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vcSex", DbType="VarChar(20)")]
		public string vcSex
		{
			get
			{
				return this._vcSex;
			}
			set
			{
				if ((this._vcSex != value))
				{
					this.OnvcSexChanging(value);
					this.SendPropertyChanging();
					this._vcSex = value;
					this.SendPropertyChanged("vcSex");
					this.OnvcSexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datDOB", DbType="Date")]
		public System.Nullable<System.DateTime> datDOB
		{
			get
			{
				return this._datDOB;
			}
			set
			{
				if ((this._datDOB != value))
				{
					this.OndatDOBChanging(value);
					this.SendPropertyChanging();
					this._datDOB = value;
					this.SendPropertyChanged("datDOB");
					this.OndatDOBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vcMobil", DbType="VarChar(100)")]
		public string vcMobil
		{
			get
			{
				return this._vcMobil;
			}
			set
			{
				if ((this._vcMobil != value))
				{
					this.OnvcMobilChanging(value);
					this.SendPropertyChanging();
					this._vcMobil = value;
					this.SendPropertyChanged("vcMobil");
					this.OnvcMobilChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vcTransp", DbType="VarChar(20)")]
		public string vcTransp
		{
			get
			{
				return this._vcTransp;
			}
			set
			{
				if ((this._vcTransp != value))
				{
					this.OnvcTranspChanging(value);
					this.SendPropertyChanging();
					this._vcTransp = value;
					this.SendPropertyChanged("vcTransp");
					this.OnvcTranspChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vcAuthNo", DbType="VarChar(20)")]
		public string vcAuthNo
		{
			get
			{
				return this._vcAuthNo;
			}
			set
			{
				if ((this._vcAuthNo != value))
				{
					this.OnvcAuthNoChanging(value);
					this.SendPropertyChanging();
					this._vcAuthNo = value;
					this.SendPropertyChanged("vcAuthNo");
					this.OnvcAuthNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datAuth", DbType="Date")]
		public System.Nullable<System.DateTime> datAuth
		{
			get
			{
				return this._datAuth;
			}
			set
			{
				if ((this._datAuth != value))
				{
					this.OndatAuthChanging(value);
					this.SendPropertyChanging();
					this._datAuth = value;
					this.SendPropertyChanged("datAuth");
					this.OndatAuthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datEffectiv", DbType="Date")]
		public System.Nullable<System.DateTime> datEffectiv
		{
			get
			{
				return this._datEffectiv;
			}
			set
			{
				if ((this._datEffectiv != value))
				{
					this.OndatEffectivChanging(value);
					this.SendPropertyChanging();
					this._datEffectiv = value;
					this.SendPropertyChanged("datEffectiv");
					this.OndatEffectivChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datExp", DbType="VarChar(20)")]
		public string datExp
		{
			get
			{
				return this._datExp;
			}
			set
			{
				if ((this._datExp != value))
				{
					this.OndatExpChanging(value);
					this.SendPropertyChanging();
					this._datExp = value;
					this.SendPropertyChanged("datExp");
					this.OndatExpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bHHA_Sun", DbType="VarChar(1)")]
		public string bHHA_Sun
		{
			get
			{
				return this._bHHA_Sun;
			}
			set
			{
				if ((this._bHHA_Sun != value))
				{
					this.OnbHHA_SunChanging(value);
					this.SendPropertyChanging();
					this._bHHA_Sun = value;
					this.SendPropertyChanged("bHHA_Sun");
					this.OnbHHA_SunChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bHHA_Mon", DbType="VarChar(1)")]
		public string bHHA_Mon
		{
			get
			{
				return this._bHHA_Mon;
			}
			set
			{
				if ((this._bHHA_Mon != value))
				{
					this.OnbHHA_MonChanging(value);
					this.SendPropertyChanging();
					this._bHHA_Mon = value;
					this.SendPropertyChanged("bHHA_Mon");
					this.OnbHHA_MonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bHHA_Tue", DbType="VarChar(1)")]
		public string bHHA_Tue
		{
			get
			{
				return this._bHHA_Tue;
			}
			set
			{
				if ((this._bHHA_Tue != value))
				{
					this.OnbHHA_TueChanging(value);
					this.SendPropertyChanging();
					this._bHHA_Tue = value;
					this.SendPropertyChanged("bHHA_Tue");
					this.OnbHHA_TueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bHHA_Wed", DbType="VarChar(1)")]
		public string bHHA_Wed
		{
			get
			{
				return this._bHHA_Wed;
			}
			set
			{
				if ((this._bHHA_Wed != value))
				{
					this.OnbHHA_WedChanging(value);
					this.SendPropertyChanging();
					this._bHHA_Wed = value;
					this.SendPropertyChanged("bHHA_Wed");
					this.OnbHHA_WedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bHHA_Thu", DbType="VarChar(1)")]
		public string bHHA_Thu
		{
			get
			{
				return this._bHHA_Thu;
			}
			set
			{
				if ((this._bHHA_Thu != value))
				{
					this.OnbHHA_ThuChanging(value);
					this.SendPropertyChanging();
					this._bHHA_Thu = value;
					this.SendPropertyChanged("bHHA_Thu");
					this.OnbHHA_ThuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bHHA_Fri", DbType="VarChar(1)")]
		public string bHHA_Fri
		{
			get
			{
				return this._bHHA_Fri;
			}
			set
			{
				if ((this._bHHA_Fri != value))
				{
					this.OnbHHA_FriChanging(value);
					this.SendPropertyChanging();
					this._bHHA_Fri = value;
					this.SendPropertyChanged("bHHA_Fri");
					this.OnbHHA_FriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bHHA_Sat", DbType="VarChar(1)")]
		public string bHHA_Sat
		{
			get
			{
				return this._bHHA_Sat;
			}
			set
			{
				if ((this._bHHA_Sat != value))
				{
					this.OnbHHA_SatChanging(value);
					this.SendPropertyChanging();
					this._bHHA_Sat = value;
					this.SendPropertyChanged("bHHA_Sat");
					this.OnbHHA_SatChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
